version = 1
SPDX-PackageName = "odg-core"
SPDX-PackageSupplier = "ospo@sap.com"
SPDX-PackageDownloadLocation = "https://github.com/open-component-model/odg-core"

[[annotations]]
path = "**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 SAP SE or an SAP affiliate company and Open Component Model contributors"
SPDX-License-Identifier = "Apache-2.0"
