- name: default
  finding_types:
    - finding/crypto
    - finding/diki
    - finding/falco
    - finding/kyverno
    - finding/ghas
    - finding/inventory
    - finding/ip
    - finding/license
    - finding/malware
    - finding/osid
    - finding/sast
    - finding/vulnerability
  special_component_ids:
    - 03e237b4-434e-4e1c-b786-5ceb6cc76c1c
