#!/usr/bin/env bash

set -eu

repo_dir="$(readlink -f "$(dirname "${BASH_SOURCE[0]}")/..")"
out_dir="$(readlink -f "${repo_dir}/../${PACKAGES_PATH:-}/dist")"
mkdir "${out_dir}"

ocm_repo='europe-docker.pkg.dev/gardener-project/releases'
cc_utils_version="$(cat "${repo_dir}/CC_UTILS_VERSION")"

apk add --no-cache xz

# retrieve packages from cc-utils from OCM (prefer over publishing via PYPI)
for resource in gardener-cicd-libs gardener-oci gardener-ocm; do
  echo "downloading ${resource}:${cc_utils_version}"
  ocm download resources \
    "OCIRegistry::${ocm_repo}//github.com/gardener/cc-utils:${cc_utils_version}" \
    "${resource}" \
    -O - | tar xJ -C"${out_dir}"
done

cd $repo_dir

# install build-only dependencies (no need to include in image)
pip3 install --upgrade pip wheel setuptools semver

# build into "${repo_dir}/dist"
python3 "${repo_dir}/setup.utils.py" bdist_wheel
rm -rf "${repo_dir}/build"
python3 "${repo_dir}/setup.service.py" bdist_wheel
rm -rf "${repo_dir}/build"
python3 "${repo_dir}/setup.extensions.py" bdist_wheel
rm -rf "${repo_dir}/build"

# keep for subsequent docker build
cp dist/* ${out_dir}
