#!/usr/bin/env bash

set -e

repo_dir="$(readlink -f "$(dirname "$0")/..")"
out_dir="$(readlink -f "${repo_dir}/../${PACKAGES_PATH:-}/dist")"
mkdir "${out_dir}"

cd $repo_dir

# install build-only dependencies (no need to include in image)
pip3 install --upgrade pip wheel setuptools semver

# build into "${repo_dir}/dist"
python3 "${repo_dir}/setup.utils.py" sdist bdist_wheel
python3 "${repo_dir}/setup.service.py" sdist bdist_wheel
python3 "${repo_dir}/setup.extensions.py" sdist bdist_wheel

# keep for subsequent docker build
cp dist/* ${out_dir} 
