#!/usr/bin/env bash

set -eu

repo_dir="$(readlink -f "$(dirname "${BASH_SOURCE[0]}")/..")"
out_dir="$(readlink -f "${repo_dir}/../${PACKAGES_PATH:-}/dist")"
mkdir "${out_dir}"

apk add --no-cache xz

cd $repo_dir

# install build-only dependencies (no need to include in image)
pip3 install --upgrade pip wheel setuptools semver

# build into "${repo_dir}/dist"
python3 "${repo_dir}/setup.bdba.py" bdist_wheel
rm -rf "${repo_dir}/build"

# keep for subsequent docker build
cp dist/* ${out_dir}
