#!/usr/bin/env bash

set -eu

repo_root="$(dirname "${BASH_SOURCE[0]}")/.."

if ! which pip3 &> /dev/null; then
  echo "pip3 is required"
  exit 1
fi

cc_utils_version="$(cat "${repo_root}/CC_UTILS_VERSION")"
bdba_version="$(cat "${repo_root}/BDBA_DEPENDENCY_VERSION")"

pkg_dir=packages
mkdir -p "${pkg_dir}"
ocm_repo='europe-docker.pkg.dev/gardener-project/releases'

for resource in gardener-cicd-libs gardener-oci gardener-ocm; do
  echo "downloading ${resource}:${cc_utils_version}"
  ocm download resources \
    "OCIRegistry::${ocm_repo}//github.com/gardener/cc-utils:${cc_utils_version}" \
    "${resource}" \
    -O - | tar xJ -C"${pkg_dir}"
done

resource=bdba
echo "downloading ${resource}:${bdba_version}"
ocm download resources \
  "OCIRegistry::${ocm_repo}//ocm.software/ocm-gear/bdba-client:${bdba_version}" \
  "${resource}" \
  -O - | tar xJ -C"${pkg_dir}"

apk add --no-cache \
  gcc \
  libc-dev \
  libev-dev \
  libffi-dev \
  py3-numpy \
  py3-scipy \
  python3-dev

pip3 install --no-cache --upgrade \
  --find-links "${pkg_dir}" \
  -r "${repo_root}/requirements.extensions.txt" \
  -r "${repo_root}/requirements.service.txt" \
  -r "${repo_root}/requirements.utils.txt" \
  pytest-asyncio
