#!/usr/bin/env bash
set -eu

# usage: $1: <src-dir>

src_dir="${1:-"$(dirname "${BASH_SOURCE[0]}")/.."}"

error=0

export PYTHONPATH="${src_dir}:${PYTHONPATH-""}"

(
    pushd "${src_dir}"
    echo "using pylama cfg at ${src_dir}/pylama.ini"
    set -x

    echo 'running pylama for bdba module (errors only)'
    if pylama -iW,R,C  -lpylint --options "${src_dir}/pylama.ini" bdba; then
        echo 'pylama succeeded'
    else
        ((error|=1))
    fi

    echo 'running flake8 for bdba module'
    if ".ci/lint-flake8" bdba; then
        echo 'pyflake8 succeeded'
    else
        ((error|=1))
    fi

    echo 'running bandit (sast-linter) for bdba module'
    if bandit \
        --configfile "${src_dir}/pyproject.toml" \
        --recursive \
        "${src_dir}/bdba" ${bandit_extra_args:-}; then
        echo "bandit succeeded"
    else
        ((error|=1))
    fi

    if [ $error -eq 0 ]; then
        exit 0
    elif [ $error -gt 0 ]; then
        exit 1
    fi
    popd
)

exit $?
