#!/usr/bin/env bash
set -eu

# usage: $1: <src-dir>

src_dir="${1:-"$(dirname "${BASH_SOURCE[0]}")/.."}"

"${src_dir}/.ci/install-dependencies"

echo 'Running flake8 for all python modules..'
error=0

export PYTHONPATH="${src_dir}"

echo 'running pylama for all modules (errors only)'
(
    pushd "${src_dir}"
    echo "using pylama cfg at ${src_dir}/pylama.ini"
    set -x
    if pylama -iW,R,C  -lpylint --options "${src_dir}/pylama.ini" "${src_dir}"; then
        echo 'pylama succeeded'
    else
        ((error|=1))
    fi

    if "${src_dir}/.ci/lint-flake8"; then
        echo 'pyflake8 succeeded'
    else
        ((error|=1))
    fi

    if [ $error -eq 0 ]; then
        exit 0
    elif [ $error -gt 0 ]; then
        exit 1
    fi
    popd
)

exit $?
