#!/bin/bash -e

set -e

if ! which pytest &>/dev/null; then
  echo "pytest is required (install with pip(3) install pytest)"
  exit 1
fi

if ! which pip3 &> /dev/null; then
  echo "pip3 is required"
  exit 1
fi

src_dir="${1:-"$(readlink -f "$(dirname "${0}")/..")"}"

pip3 install -r "${src_dir}/requirements.utils.txt"
pip3 install -r "${src_dir}/requirements.service.txt"
pip3 install -r "${src_dir}/requirements.extensions.txt"


if PYTHONPATH="${src_dir}:${PYTHONPATH:-}" pytest "${src_dir}" "${@}"; then
    echo 'Unittest executions succeeded'
    exit 0
else
    echo 'Errors were found whilst executing unittests (see above)'
    exit 1
fi
