#!/usr/bin/env bash

set -eu

repo_root="$(dirname "${BASH_SOURCE[0]}")/.."

if ! which pytest &>/dev/null; then
  echo "pytest is required (install with pip(3) install pytest)"
  exit 1
fi

if PYTHONPATH="${repo_root}:${PYTHONPATH:-}" pytest "${repo_root}" "${@}"; then
  echo 'Unittest executions succeeded'
  exit 0
else
  echo 'Errors were found whilst executing unittests (see above)'
  exit 1
fi
