#!/usr/bin/env bash

read -r next_version

echo "$next_version" > "$(dirname "$0")/../VERSION"

extension_definitions="$(dirname "$0")/../extension-definitions.yaml"

# pass env-var inline to make it available in yq subprocess
NEXT_VERSION="$next_version" yq -i '
    .installation.ocm_references[].version = strenv(NEXT_VERSION) |
    .installation.ocm_references[].artefact.version = strenv(NEXT_VERSION) |
    .installation.ocm_references[].mappings[].version = strenv(NEXT_VERSION)
' "${extension_definitions}"
