apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-delivery-db-0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: standard
  volumeMode: Filesystem
