apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: backlogitems.delivery-gear.gardener.cloud
  annotations:
    resources.gardener.cloud/keep-object: "true"
spec:
  group: delivery-gear.gardener.cloud
  scope: Namespaced
  names:
    singular: backlogitem
    plural: backlogitems
    kind: BacklogItem
    shortNames:
      - bli
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              # enable additional properties not being pruned to allow adding
              # of new properties in the future as helm won't upgrade crds
              x-kubernetes-preserve-unknown-fields: true
              type: object
              properties:
                timestamp:
                  type: string
                artefact:
                  x-kubernetes-preserve-unknown-fields: true
                  type: object
                  properties:
                    component_name:
                      type: string
                    component_version:
                      type: string
                    artefact_kind:
                      type: string
                    artefact:
                      x-kubernetes-preserve-unknown-fields: true
                      type: object
                      properties:
                        artefact_name:
                          type: string
                        artefact_version:
                          type: string
                        artefact_type:
                          type: string
                        artefact_extra_id:
                          x-kubernetes-preserve-unknown-fields: true
                          type: object
                    references:
                      type: array
                      items:
                        x-kubernetes-preserve-unknown-fields: true
                        type: object
                priority:
                  type: integer
      additionalPrinterColumns:
        - name: Priority
          type: integer
          jsonPath: .spec.priority
          priority: 0
        - name: Claimed
          type: string
          jsonPath: '.metadata.labels.delivery-gear\.gardener\.cloud/claimed'
          priority: 0
        - name: Component
          type: string
          jsonPath: .spec.artefact.component_name
          priority: 1
        - name: Version
          type: string
          jsonPath: .spec.artefact.component_version
          priority: 1
        - name: Artefact
          type: string
          jsonPath: .spec.artefact.artefact.artefact_name
          priority: 1
        - name: Version
          type: string
          jsonPath: .spec.artefact.artefact.artefact_version
          priority: 1
        - name: Type
          type: string
          jsonPath: .spec.artefact.artefact.artefact_type
          priority: 1
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
          priority: 0
