apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: logcollections.delivery-gear.gardener.cloud
spec:
  group: delivery-gear.gardener.cloud
  scope: Namespaced
  names:
    singular: logcollection
    plural: logcollections
    kind: LogCollection
    shortNames:
      - lc
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              # enable additional properties not being pruned to allow adding
              # new properties in the future as helm won't upgrade crds
              x-kubernetes-preserve-unknown-fields: true
              type: object
              properties:
                service: # bdba, issueReplicator, clamav, ...
                  type: string
                logLevel:
                  type: string
                logs:
                  type: array
                  items:
                    x-kubernetes-preserve-unknown-fields: true
                    type: object
                    properties:
                      timestamp:
                        type: string
                      name:
                        type: string
                      logLevel:
                        type: string
                      thread:
                        type: string
                      message:
                        type: string
