apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: opendeliverygears.open-delivery-gear.ocm.software
spec:
  group: open-delivery-gear.ocm.software
  scope: Namespaced
  names:
    singular: opendeliverygear
    plural: opendeliverygears
    shortNames:
    - odg
    - odgs
    kind: ODG
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                context:
                  type: object
                  properties:
                    base_url:
                      type: string
                    deliveryServiceMaxReplicas:
                      type: integer
                    deliveryServiceMinReplicas:
                      type: integer
                    target_namespace:
                      type: string
                    keep_clusterwide_objects:
                      type: boolean
                      default: false
                  required:
                    - base_url
                    - target_namespace
                extensions:
                  type: array
                  items:
                    type: string
                    enum:
                    - access-manager
                    - artefact-enumerator
                    - backlog-controller
                    - bdba
                    - blackduck
                    - cache-manager
                    - crypto
                    - delivery-dashboard
                    - delivery-db
                    - delivery-db-backup
                    - delivery-service
                    - ghas
                    - issue-replicator
                    - malware-scanner
                    - nginx-ingress-controller
                    - osid
                    - prometheus-operator
                    - responsibles
                    - sast
            status:
              type: object
              properties:
                state:
                  type: string
                phase:
                  type: string
                error:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                extension_status:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                last_reconcile:
                  type: string
      additionalPrinterColumns:
        - name: State
          type: string
          jsonPath: .status.state
        - name: Phase
          type: string
          jsonPath: .status.phase
        - name: Last Reconcile
          type: date
          jsonPath: .status.last_reconcile
      subresources:
        status: {}
