{{- $podName := "clamav" }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $podName }}
  namespace: {{ .Values.target_namespace | default .Release.Namespace }}
spec:
  replicas: 0 # will be scaled automatically by backlog-controller
  selector:
    matchLabels:
      app: {{ $podName }}
      delivery-gear.gardener.cloud/service: clamav
  template:
    metadata:
      labels:
        app: {{ $podName }}
        delivery-gear.gardener.cloud/service: clamav
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: {{ $podName }}
      terminationGracePeriodSeconds: 1800 # 30 min
      containers:
        - name: {{ $podName }}
          image: {{ include "image" .Values.image }}
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
          env:
            - name: SECRET_FACTORY_PATH
              value: /secrets
            - name: EXTENSIONS_CFG_PATH
              value: /extensions_cfg/extensions_cfg
            - name: FINDINGS_CFG_PATH
              value: /findings_cfg/findings_cfg
            - name: OCM_REPO_MAPPINGS_PATH
              value: /ocm_repo_mappings/ocm_repo_mappings
            - name: K8S_TARGET_NAMESPACE
              value: {{ .Values.target_namespace | default .Release.Namespace }}
          volumeMounts:
            - name: aws
              mountPath: /secrets/aws
            - name: github
              mountPath: /secrets/github
            - name: kubernetes
              mountPath: /secrets/kubernetes
            - name: oci-registry
              mountPath: /secrets/oci-registry
            - name: extensions-cfg
              mountPath: /extensions_cfg
            - name: findings-cfg
              mountPath: /findings_cfg
            - name: ocm-repo-mappings
              mountPath: /ocm_repo_mappings
              readOnly: true
            - name: freshclam-config
              mountPath: /etc/clamav/freshclam.conf
              subPath: freshclam
          lifecycle:
            preStop: # hook ensures that just created pods have at least enough time alive to add a termination signal handler
              exec:
                command:
                  - sleep
                  - "60"
          resources:
            requests:
              memory: 2Gi
              cpu: 500m
            limits:
              memory: 8Gi
              cpu: 2000m
      volumes:
        - name: aws
          secret:
            secretName: secret-factory-aws
            optional: true # aws client is optional
        - name: github
          secret:
            secretName: secret-factory-github
        - name: kubernetes
          secret:
            secretName: secret-factory-kubernetes
            optional: true # might use incluster config
        - name: oci-registry
          secret:
            secretName: secret-factory-oci-registry
        - name: extensions-cfg
          configMap:
            name: extensions-cfg
        - name: findings-cfg
          configMap:
            name: findings-cfg
        - name: ocm-repo-mappings
          configMap:
            name: ocm-repo-mappings
        - name: freshclam-config
          configMap:
            name: clamav-freshclam-config
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-egress-from-clamav
  namespace: {{ .Values.target_namespace | default .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app: {{ $podName }}
  policyTypes:
    - Egress
  egress:
    - {}  # Allows all egress traffic to any destination and port
