apiVersion: v1
kind: ConfigMap
metadata:
  name: clamav-freshclam-config
data:
  freshclam: |-
    DatabaseMirror freshclam.{{ .Release.Namespace }}.svc.cluster.local:8080
    PrivateMirror freshclam.{{ .Release.Namespace }}.svc.cluster.local:8080
