apiVersion: v1
kind: Service
metadata:
  name: freshclam
  labels:
    app: freshclam
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      name: default
  selector:
    app: freshclam
