apiVersion: apps/v1
kind: Deployment
metadata:
  name: freshclam
  namespace: {{ .Values.target_namespace | default .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: freshclam
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
  template:
    metadata:
      labels:
        app: freshclam
    spec:
      containers:
        - name: freshclam
          image: {{ include "image" .Values.freshclam.image }}
          imagePullPolicy: IfNotPresent
          startupProbe:
            httpGet:
              path: /readiness
              port: 8080
            failureThreshold: 12
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readiness
              port: 8080
            periodSeconds: 10
            timeoutSeconds: 3
          ports:
            - containerPort: 8080
              name: default
          resources:
            requests:
              memory: 500Mi
              cpu: 1000m
            limits:
              memory: 1Gi
              cpu: 1500m
