apiVersion: v1
kind: ConfigMap
metadata:
  name: clamav-freshclam-config
  namespace: {{ .Values.target_namespace | default .Release.Namespace }}
data:
  freshclam: |-
    DatabaseMirror freshclam.{{ .Values.target_namespace | default .Release.Namespace }}.svc.cluster.local:8080
    PrivateMirror freshclam.{{ .Values.target_namespace | default .Release.Namespace }}.svc.cluster.local:8080
