apiVersion: apps/v1
kind: Deployment
metadata:
  name: backlog-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backlog-controller
  template:
    metadata:
      labels:
        app: backlog-controller
    spec:
      containers:
        - name: backlog-controller
          image: {{ include "image" (index .Values "backlog-controller" "image") }} # indexing required since `-` is not allowed in variable names
          imagePullPolicy: IfNotPresent
          command:
          - python3
          - -m
          - backlog_controller
          {{- if default dict .Values.envVars }}
          env:
          {{- range $key, $value := .Values.envVars }}
          - name: {{ $key }}
            value: {{ $value }}
          {{- end }}
          {{- end }}
          volumeMounts:
          - name: kubernetes
            mountPath: /secrets/kubernetes
          - name: cfg-factory
            mountPath: "/cfg_factory"
            readOnly: true
          resources:
            requests:
              memory: 100Mi
              cpu: 30m
            limits:
              memory: 300Mi
              cpu: 300m
      volumes:
        - name: kubernetes
          secret:
            secretName: secret-factory-kubernetes
            optional: true # might use incluster config
        - name: cfg-factory
          secret:
            secretName: cfg-factory-secret
            optional: true
