apiVersion: apps/v1
kind: Deployment
metadata:
  name: backlog-controller
  namespace: {{ .Values.target_namespace | default .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backlog-controller
  template:
    metadata:
      labels:
        app: backlog-controller
    spec:
      containers:
        - name: backlog-controller
          image: {{ include "image" .Values.image }}
          imagePullPolicy: IfNotPresent
          command:
            - python3
            - -m
            - backlog_controller
          env:
            - name: SECRET_FACTORY_PATH
              value: /secrets
            - name: EXTENSIONS_CFG_PATH
              value: /extensions_cfg/extensions_cfg
            - name: K8S_TARGET_NAMESPACE
              value: {{ .Values.target_namespace | default .Release.Namespace }}
          volumeMounts:
            - name: kubernetes
              mountPath: /secrets/kubernetes
            - name: extensions-cfg
              mountPath: /extensions_cfg
          resources:
            requests:
              memory: 100Mi
              cpu: 30m
            limits:
              memory: 300Mi
              cpu: 300m
      volumes:
        - name: kubernetes
          secret:
            secretName: secret-factory-kubernetes
            optional: true # might use incluster config
        - name: extensions-cfg
          configMap:
            name: extensions-cfg
