{{- $podName := "backlog-controller" }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $podName }}
  namespace: {{ .Values.target_namespace | default .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $podName }}
  template:
    metadata:
      labels:
        app: {{ $podName }}
    spec:
      containers:
        - name: {{ $podName }}
          image: {{ include "image" .Values.image }}
          imagePullPolicy: IfNotPresent
          command:
            - python3
            - -m
            - backlog_controller
          securityContext:
            allowPrivilegeEscalation: false
          env:
            - name: SECRET_FACTORY_PATH
              value: /secrets
            - name: EXTENSIONS_CFG_PATH
              value: /extensions_cfg/extensions_cfg
            - name: K8S_TARGET_NAMESPACE
              value: {{ .Values.target_namespace | default .Release.Namespace }}
          volumeMounts:
            - name: kubernetes
              mountPath: /secrets/kubernetes
            - name: extensions-cfg
              mountPath: /extensions_cfg
          resources:
            requests:
              memory: 100Mi
              cpu: 30m
            limits:
              memory: 300Mi
              cpu: 300m
      volumes:
        - name: kubernetes
          secret:
            secretName: secret-factory-kubernetes
            optional: true # might use incluster config
        - name: extensions-cfg
          configMap:
            name: extensions-cfg
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-egress-from-backlog-controller
  namespace: {{ .Values.target_namespace | default .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app: {{ $podName }}
  policyTypes:
    - Egress
  egress:
    - {}  # Allows all egress traffic to any destination and port
