apiVersion: v2
name: extensions
version: 0.1.0
dependencies:
  - name: access-manager
    repository: file://charts/access-manager
    condition: access-manager.enabled
  - name: artefact-enumerator
    repository: file://charts/artefact-enumerator
    condition: artefact-enumerator.enabled
  - name: backlog-controller
    repository: file://charts/backlog-controller
    condition: backlog-controller.enabled
  - name: bdba
    repository: file://charts/bdba
    condition: bdba.enabled
  - name: cache-manager
    repository: file://charts/cache-manager
    condition: cache-manager.enabled
  - name: clamav
    repository: file://charts/clamav
    condition: clamav.enabled
  - name: crypto
    repository: file://charts/crypto
    condition: crypto.enabled
  - name: delivery-db-backup
    repository: file://charts/delivery-db-backup
    condition: delivery-db-backup.enabled
  - name: issue-replicator
    repository: file://charts/issue-replicator
    condition: issue-replicator.enabled
  - name: sast
    repository: file://charts/sast
    condition: sast.enabled
  - name: osid
    repository: file://charts/osid
    condition: osid.enabled
  - name: responsibles
    repository: file://charts/responsibles
    condition: responsibles.enabled
