global:
  # image property will be set during release
  image:
    ref: null
    repository: null
    tag: null

access-manager:
  enabled: false
artefact-enumerator:
  enabled: false
backlog-controller:
  enabled: false
bdba:
  deployment:
    annotations: []
  enabled: false
cache-manager:
  enabled: false
clamav:
  deployment:
    annotations: []
  enabled: false
  freshclam:
    image:
      repository: null
      tag: null
crypto:
  deployment:
    annotations: []
  enabled: false
delivery-db-backup:
  enabled: false
ghas:
  enabled: false
issue-replicator:
  deployment:
    annotations: []
  enabled: false
odg-operator:
  enabled: false
  extensionDefinitions: null
  namespaceOverride: null
osid:
  deployment:
    annotations: []
  enabled: false
responsibles:
  deployment:
    annotations: []
  enabled: false
sast:
  deployment:
    annotations: []
  enabled: false
sla-violation-profiler:
  enabled: false
  schedule: null
  target_namespace: null
  ttl_seconds_after_finished: null
  successful_jobs_history_limit: null
  failed_jobs_history_limit: null
  backoff_limit: null
sbom-generator:
  deployment:
    annotations: []
  enabled: false
