config:
  global:
    scrape_interval: 15s
  scrape_configs:
  - job_name: delivery_service
    static_configs:
    - targets:
      - delivery-service.delivery.svc.cluster.local:8080

ingress:
  class: nginx
  hosts:
    - prometheus
