access-manager:
  enabled: False
artefact-enumerator:
  enabled: False
backlog-controller:
  enabled: True
bdba:
  enabled: False
cache-manager:
  enabled: False
clamav:
  enabled: False
crypto:
  enabled: False
delivery-db-backup:
  enabled: False
ghas:
  enabled: False
issue-replicator:
  enabled: False
odg-operator:
  enabled: False
osid:
  enabled: True
responsibles:
  enabled: True
sast:
  enabled: True
