ingress:
  class: nginx
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 8m
    nginx.ingress.kubernetes.io/proxy-read-timeout: '"900"'
    nginx.ingress.kubernetes.io/proxy-next-upstream: error timeout http_503
    nginx.ingress.kubernetes.io/proxy-next-upstream-timeout: '"0"'
    nginx.ingress.kubernetes.io/proxy-next-upstream-tries: '"0"'
  disableTls: True
  hosts:
    - delivery-service

additionalVolumes:
  - name: sprints
    configMap:
      name: sprints
      optional: true
  - name: addressbook
    configMap:
      name: addressbook
      optional: true
  - name: github-mappings
    configMap:
      name: github-mappings
      optional: true

additionalVolumeMounts:
  - name: sprints
    mountPath: "/sprints"
  - name: addressbook
    mountPath: "/addressbook"
  - name: github-mappings
    mountPath: "/github_mappings"

featuresCfg:
  specialComponents:
    - id: f7e84fdb-69fe-4837-b1c2-58cf4e58e5c7
      name: ocm.software/ocm-gear
      displayName: OCM Gear
      type: OCM Gear
      version: greatest
      icon: home
      dependencies: []
    - id: 8ca887cf-0d09-4f28-bc88-727aa3e30a26
      name: ocm.software/ocmcli
      displayName: OCM Cli
      type: OCM Core
      version: greatest
      icon: home
      dependencies: []
  addressbook:
    addressbookRelpath: ./../../../../addressbook/addressbook
    githubMappingsRelpath: ./../../../../github_mappings/github_mappings
  sprints:
    sprintsRelpath: ./../../../../sprints/sprints
    sprintDateNameMappings:
      - dateName: release_decision
        displayName: Release Decision
      - dateName: end_date
        displayName: End Date
