apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ingress-to-delivery-service
  namespace: {{ .Values.target_namespace | default .Release.Namespace }}
spec:
  podSelector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - delivery-service
  policyTypes:
    - Ingress
  ingress:
  - ports:
    - protocol: TCP
      port: 8080