apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-egress-from-delivery-service
  namespace: {{ .Values.target_namespace | default .Release.Namespace }}
spec:
  podSelector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - delivery-service
  policyTypes:
    - Egress
  egress:
    - {}  # Allows all egress traffic to any destination and port
