apiVersion: v1
kind: Service
metadata:
  name: delivery-service
  namespace: {{ .Values.target_namespace | default .Release.Namespace }}
  labels:
    app: delivery-service
spec:
  type: ClusterIP
  ports:
  - port: {{ default 8080 .Values.servicePort }}
    targetPort: {{ default 5000 .Values.containerPort }}
    name: default
  selector:
    app: delivery-service
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: delivery-service
  namespace: {{ .Values.target_namespace | default .Release.Namespace }}
spec:
  parentRefs:
    - name: {{ default "open-delivery-gear" .Values.gatewayName }}
  hostnames:
    - {{ .Values.host }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: delivery-service
          port: {{ default 8080 .Values.servicePort }}
      timeouts:
        request: 15m
      retry:
        codes: [502, 503, 504]
        attempts: 3
