apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery-service
spec:
  selector:
    matchLabels:
      app: delivery-service
  strategy:
    type: RollingUpdate
  template:
    metadata:
      {{- if default dict (.Values.pod).annotations }}
      annotations:
      {{- range $annotation, $value := .Values.pod.annotations }}
        {{ $annotation }}: {{ $value }}
      {{- end }}
      {{- end }}
      labels:
        app: delivery-service
      {{- if default dict (.Values.pod).labels }}
      {{- range $annotation, $value := .Values.pod.labels }}
        {{ $annotation }}: {{ $value }}
      {{- end }}
      {{- end }}
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: delivery-service
      containers:
        - name: delivery-service
          image: {{ include "image" .Values.image }}
          imagePullPolicy: IfNotPresent
          args:
            - --productive
          {{- range $arg := default list .Values.args }}
            - {{ $arg }}
          {{- end }}
          readinessProbe:
            httpGet:
              path: /ready
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
          ports:
            - containerPort: {{ default 5000 .Values.containerPort }}
              name: default
          env:
          - name: SECRET_FACTORY_PATH
            value: /secrets
          - name: EXTENSIONS_CFG_PATH
            value: /extensions_cfg/extensions_cfg
          - name: FINDINGS_CFG_PATH
            value: /findings_cfg/findings_cfg
          - name: FEATURES_CFG_PATH
            value: /features_cfg/features_cfg
          - name: OCM_REPO_MAPPINGS_PATH
            value: /ocm_repo_mappings/ocm_repo_mappings
          - name: K8S_TARGET_NAMESPACE
            value: {{ .Release.Namespace }}
          {{- if default dict .Values.envVars }}
          {{- range $key, $value := .Values.envVars }}
          - name: {{ $key }}
            value: {{ $value }}
          {{- end }}
          {{- end }}
          volumeMounts:
            - name: bdba
              mountPath: /secrets/bdba
            - name: delivery-db
              mountPath: /secrets/delivery-db
            - name: github
              mountPath: /secrets/github
            - name: kubernetes
              mountPath: /secrets/kubernetes
            - name: oauth-cfg
              mountPath: /secrets/oauth-cfg
            - name: oci-registry
              mountPath: /secrets/oci-registry
            - name: signing-cfg
              mountPath: /secrets/signing-cfg
            - name: extensions-cfg
              mountPath: /extensions_cfg
            - name: findings-cfg
              mountPath: /findings_cfg
            - name: ocm-repo-mappings
              mountPath: /ocm_repo_mappings
            - name: features-cfg
              mountPath: "/features_cfg"
          {{- if .Values.additionalVolumeMounts }}
            {{- toYaml .Values.additionalVolumeMounts | nindent 12 }}
          {{- end }}
          resources:
            requests:
              memory: 1Gi
              cpu: 100m
            limits:
              memory: 5Gi
              cpu: 500m
      volumes:
        - name: bdba
          secret:
            secretName: secret-factory-bdba
            optional: true # bdba extension is optional
        - name: delivery-db
          secret:
            secretName: secret-factory-delivery-db
        - name: github
          secret:
            secretName: secret-factory-github
        - name: kubernetes
          secret:
            secretName: secret-factory-kubernetes
            optional: true # extensions in general are optional
        - name: oauth-cfg
          secret:
            secretName: secret-factory-oauth-cfg
            optional: true # authentication is optional
        - name: oci-registry
          secret:
            secretName: secret-factory-oci-registry
        - name: signing-cfg
          secret:
            secretName: secret-factory-signing-cfg
            optional: true # authentication is optional
        - name: extensions-cfg
          configMap:
            name: extensions-cfg
        - name: findings-cfg
          configMap:
            name: findings-cfg
        - name: ocm-repo-mappings
          configMap:
            name: ocm-repo-mappings
        - name: features-cfg
          secret:
            secretName: features-cfg
            optional: true
      {{- if .Values.additionalVolumes }}
        {{- toYaml .Values.additionalVolumes | nindent 8 }}
      {{- end }}
