# Taken from https://docs.clamav.net/appendix/CvdPrivateMirror.html#use-freshclam-to-serve-only-whole-database-files-from-a-private-mirror

# The private mirror will update from database.clamav.net.
DatabaseMirror database.clamav.net

# Customize the DatabaseDirectory so that FreshClam will update the DocumentRoot.
DatabaseDirectory /www

# Enable CLD compression to save bandwidth between your mirror and your clients.
CompressLocalDatabase yes

UpdateLogFile /freshclam/freshclam.log

# Run command after successful database update.
# Default: disabled
OnUpdateExecute echo up-to-date > /freshclam/status

# Run command when freshclam reports outdated version.
# In the command string %v will be replaced by the new version number.
# Default: disabled
OnOutdatedExecute echo outdated > /freshclam/status; sleep 10

# Number of database checks per day.
# Default: 12 (every two hours)
Checks 2
