delivery_service:
  # bdba: local
  container_registry:
    config_names:
      - local
  delivery: local
  delivery_db: local
  delivery_endpoints: local
  github:
    config_names:
      - github_com
