name: CI (non-release)
on:
  push:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yaml
    permissions:
      contents: read
      packages: write
      id-token: write
    with:
      mode: snapshot
      version-prerelease: "${commit_digest}"
      version-commit-message: "build ${version}"

  post-build:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: component-descriptor
        uses: gardener/cc-utils/.github/actions/merge-ocm-fragments@master
        with:
          component-descriptor: ${{ needs.build.outputs.base-component-descriptor }}
