name: CI (non-release)
on:
  pull_request_target:
  push:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yaml
    permissions:
      contents: write
      packages: write
      id-token: write
    with:
      mode: snapshot

  component-descriptor:
    uses: gardener/cc-utils/.github/workflows/post-build.yaml@v1
    needs:
      - build
    permissions:
      contents: write
      id-token: write
