name: Publish BDBA Client
on:
  workflow_dispatch:

jobs:
  pypi:
    runs-on: ubuntu-latest
    name: Publish to PyPI
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: gardener/cc-utils/.github/actions/install-gardener-gha-libs@master
      - name: Retrieve Distribution Package
        run: |
          set -eu

          pkg_dir=dist
          mkdir -p ${pkg_dir}
          pkg_dir="$(readlink -f ${pkg_dir})"

          ocm_repo=europe-docker.pkg.dev/gardener-project/releases
          bdba_version="$(cat "BDBA_DEPENDENCY_VERSION")"

          python -m ocm download resource \
            --ocm-repository "${ocm_repo}" \
            --component "ocm.software/ocm-gear/bdba-client:${bdba_version}" \
            --name bdba \
            | tar xJ -C "${pkg_dir}"

          echo "Retrieved package:"
          ls "${pkg_dir}"
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1 # assumes package to be located in `dist/`
