name: Release Client Package
on:
  workflow_dispatch:
    inputs:
      client:
        type: choice
        options:
          - bdba

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Update Python Package
    permissions:
      id-token: write
    steps:
      - uses: gardener/cc-utils/.github/actions/trusted-checkout@v1
        with:
          token-server: ${{ vars.FEDERATED_GITHUB_ACCESS_TOKEN_SERVER }}
          github-auth-token-permissions: |
            contents: write
          init-git-identity: true
      - name: Install setuptools and semver
        shell: bash
        run: |
          pip3 install \
            setuptools \
            semver
      - name: Create Distribution Package
        shell: bash
        run: |
          set -euo pipefail

          pkg_dir=dist
          mkdir -p ${pkg_dir}
          pkg_dir="$(readlink -f ${pkg_dir})"

          path="setup.${{ inputs.client }}-client.py"

          echo "Building distribution package from ${path} to ${pkg_dir}"
          python3 ${path} \
            bdist_wheel \
            --dist-dir ${pkg_dir}

          echo "Built package:"
          ls "${pkg_dir}"
      - name: Upload Distribution Package
        uses: actions/upload-artifact@v4
        with:
          name: distribution-package
          path: dist/
      - name: Retrieve Version
        id: version
        shell: python
        run: |
          import os
          import semver

          version_file = '${{ inputs.client }}_CLIENT_VERSION'.upper()

          with open(version_file) as f:
            from_version = f.read().strip()

          to_version = semver.Version.parse(from_version).bump_minor()

          with open(os.environ['GITHUB_OUTPUT'], 'a') as f:
            f.write(f'from-version={from_version}\n')
            f.write(f'to-version={to_version}\n')
            f.write(f'version-file={version_file}\n')
      - name: Update Version
        shell: bash
        run: |
          from_version=${{ steps.version.outputs.from-version }}
          to_version=${{ steps.version.outputs.to-version }}
          version_file=${{ steps.version.outputs.version-file }}

          echo "$to_version" > "$version_file"

          git add "$version_file"
          git commit -m "Upgrade ${{ inputs.client }} client" -m "from ${from_version} to ${to_version}"
          git push

  pypi:
    runs-on: ubuntu-latest
    name: Publish to PyPI
    needs:
      - build
    permissions:
      id-token: write
    steps:
      - name: Retrieve Distribution Package
        uses: actions/download-artifact@v4
        with:
          name: distribution-package
          path: dist
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1 # assumes package to be located in `dist/`
